---
title: "Creating graphs in R with 'ggplot2'"
author: "Robert Lazo"
date: "10/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
```


```{r setup, include=FALSE}
ca_np <- read_csv(here("data", "ca_np.csv"))

names(ca_np)
head(ca_np)
summary(ca_np)

ci_np <- read_excel(here("data", "ci_np.xlsx"))

View(ci_np)

names(ci_np)

head(ci_np)

summary(ci_np)

ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))


gg_base

gg_base +
  geom_point()

gg_base + 
  geom_col()

gg_base +
  geom_area()


gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )

gg_base + 
  geom_point(color = "purple",
             pch = 17,
             size = 4,
             alpha = 0.5)

gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )

gg_base + 
  geom_col(aes(fill = visitors))
gg_base + 
  geom_col(aes(fill = visitors))

gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  ) +
  theme_minimal()

gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )

gg_base +
  geom_line(color = "purple") +
  geom_point(color = "orange",
             aes(size = year),
             alpha = 0.5)

gg_base +
  geom_col(fill = "orange",
           color = "purple") +
  geom_line(color = "green")

ggplot(data = ca_np, aes(x = year, y = visitors)) +
  geom_line()

gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)

```

